### ISSUE TITLE
[juju] detect primary juju application

### ISSUE THREAD

**Issue by brettmilford** [canonical/hotsos#129]
Detect primary juju application and add this information to the summary.
Would be useful for determining a sosreports function at a glance.

**Comment by dosaboy** [comment]
@brettmilford any chance you could provide an example of how you would want this displayed?

**Comment by dosaboy** [comment]
@brettmilford i did some work recently to make it so that the services/processes output only includes services running on the host i.e. not including those running in containers on that host. That information, combined with the contents of juju.charms is usually enough to determine the primary function of a host. Based on that i'll go ahead and close this out. Please re-open with some example of what you are after if this isn't enough for you.
