### ISSUE TITLE
[system] Identify the virtualization technology (physical, VM, container)

### ISSUE THREAD

**Issue by slashdd** [canonical/hotsos#179]
This can be reported by `systemd-detect-virt`.

hotsos output:
```
system:
   virt: lxc
```

**Comment by dosaboy** [comment]
we already have this (see "virtualisation: lxc"):

ubuntu@snapcraft:~$ hotsos --system
INFO: analysing localhost since no sosreport path provided  
hotsos:
  version: 355
  repo-info: 394583a
system:
  hostname: snapcraft
  os: ubuntu focal
  num-cpus: 8
  load: 1.08, 1.00, 1.03
  virtualisation: lxc
  rootfs: /dev/mapper/ubuntu--vg-root 501460184 456285172  19632564  96% /
  unattended-upgrades: ENABLED
  sysctl-mismatch:
    kernel.pid_max:
      actual: '32768'
      expected: '4194304'
  potential-issues:
    - desc: host sysctl not consistent with contents of systcl.d
      origin: system.checks
      type: SysCtlWarning

INFO: see --help for more options
