### ISSUE TITLE
Simplify `tox` test?

### ISSUE THREAD

**Issue by nicolasbock** [canonical/hotsos#217]
1. Why are we using the `file` binary to decide whether the file is indeed a Python script,
https://github.com/canonical/hotsos/blob/46fc213efef537cd28ce11cf538e348b99c1b59d/tools/test/run_pylint.sh#L11
when we could rely on the file extension?
2. More importantly, the script could be simplified and instead of `find` it could use
```bash
git ls-files '*.py'
```

**Comment by dosaboy** [comment]
Using git ls-files will not include files that are not staged for commit. This would be a problem e.g. if you were writing new files that you wanted to test but had not yet staged or commited. A better option would be to simply use 'find -name *.py'. The back ground to why we use the current method is from when hotsos supported running scripts written in any language which is no longer needed since this is now an all-python app (aside from the bash runner ;)).

**Comment by hemanthnakkina** [comment]
Submitted a new commit to  add following options to get untracked files 
git ls-files --others --exclude-standard *.py
