### ISSUE TITLE
Not clear what action needs to be taken for `unbalanced crush buckets` warning

### ISSUE THREAD

**Issue by nobuto-m** [canonical/hotsos#284]
We've got the following warning from hotsos. However, the description wasn't crystal clear what needs to be checked in the crush map nor what action needs to be taken to remediate the situation (if it's not a false positive).

```
  potential-issues:
    CephCrushWarnings:
      - unbalanced crush buckets identified in CRUSH root 'default' using failure
        domain 'rack'. Affected CRUSH rule id is '0'. This can cause data distribution
        to become skewed - please check crush map (origin=storage.ceph_cluster_checks)
```

**Comment by pponnuvel** [comment]
@nobuto-m Can you share `ceph osd crush dump -f json-pretty` where this happens?

**Comment by nobuto-m** [comment]
Unfortunately this was an air-gapped deployment and we weren't able to spot the original sosreport stored somewhere, but we only have hotsos output.

**Comment by KellenRenshaw** [comment]
I have been working on trying to be clearer in the output as to where one should look in the Ceph cluster's CRUSH map to determine if the check is alerting on something that does need remediation.

@nobuto-m 
Is this output easier to understand? It is for a test case configured for rack failure domains that are deliberately different to cause the check to be raised.
```
Found one or more unbalanced buckets in the cluster's CRUSH map.
This can cause uneven data distribution in the cluster. 
Verify that "ceph osd crush tree --show-shadow" conforms to the expected layout for the cluster.
Transient issues such as "out" OSDs, or cluster expansion/maintenance can trigger this warning.
Affected CRUSH tree(s) and bucket types are tree default at the rack buckets.
```

I don't currently see a way that this check can provide remediation information. That would require the check (and therefore hotsos) to know the desired state of the cluster.

We know that having all the buckets (at the configured failure domains) be the same size (or of size 0) is the optimal case, thus we alert on differences from that optimal case. However, the check has no way of knowing if those differences are intentional, transient, or the result of error.

For example, if the check finds that a set of buckets are of differing sizes, it doesn't have a way to know what the "correct" size should be.

**Comment by nobuto-m** [comment]
A potential cause of triggering this warning in the specific deployment was 20 nodes were distributed into 3 racks as 7+7+6. Was that case to surface it from a code point of view? If so, we might want to see the actual number in the output so we can clearly know why it was triggered and can triage it appropriately.
