### ISSUE TITLE
warn on ceph-mgr if "ceph osd df tree" is not showing up on monitor's sosreport

### ISSUE THREAD

**Issue by taodd** [canonical/hotsos#300]
When ceph-mgr is hang or down, the "ceph osd df tree" might be hanging and there wouldn't be an output file on the monitor's sosreport. 
So, we should warn the user that a restart of ceph-mgr might be required if we don't see the ceph_osd_df_tree file in the sosreport.

**Comment by pponnuvel** [comment]
Plenty of (sos report) ceph commands can hang if ceph-mgr is experiencing problems or unreponsive. So we should probably expand this check widely (not just "ceph osd df tree").

**Comment by dosaboy** [comment]
In the case of sosreport, would the outcome not be that the ceph plugin would timeout? In which case we would see this in https://github.com/canonical/hotsos/blob/c88375d8700bf53faed4e5de55c34bd0bdc66187/core/plugins/sosreport.py#L43

**Comment by pponnuvel** [comment]
> In the case of sosreport, would the outcome not be that the ceph plugin would timeout? In which case we would see this in
> 
> https://github.com/canonical/hotsos/blob/c88375d8700bf53faed4e5de55c34bd0bdc66187/core/plugins/sosreport.py#L43

Yes, that's a strong indicator of unresponsive mgr.

It's also possible that the active one hangs (in response to a command) and a standby mgr becomes active frequently which might be able to process subsequent command(s). So if _any_ of the ceph_osd_* or ceph_pg_* files are empty on mon's sosreport, that's also a sign of problematic mgr (because we always expect these cmds to work and contain data when run from a mon node).
