### ISSUE TITLE
Collect info on D-state processes

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#381]
If hosts have D-state processes that can often indicate a problem so we could at least include that info in the summary.

**Comment by nkshirsagar** [comment]
Temporary D state processes are normal, so in those cases we should not flag a warning. They could exist when the sos was taken, and clear up immediately afterwarrds..

The problem is when D state processes end up blocked for longer than the (default) 120s in which case a blocked task trace will be seen in the logs, which will be caught by the "has_stacktraces" hotsos check. 

~~~
checks:
  has_stacktraces:
    property:
      path: hotsos.core.plugins.kernel.CallTraceManager.calltrace_anytype
      ops: [[length_hint]]
<snip>
conclusions:
  stacktraces:
    # Give this one lowest priority so that if any other call trace types match they
    # take precedence.
    priority: 1
    decision: has_stacktraces
    raises:
      type: KernelError
      message: >-
        {numreports} reports of stacktraces in kern.log - please check.
      format-dict:
        numreports: '@checks.has_stacktraces.requires.value_actual:len'
~~~

There is also https://github.com/canonical/hotsos/issues/198 (WIP) to report any blocked tasks, which should take care of the scenario where a D state process has been blocked too long. 

So I wonder if this issue will help hotsos provide any additional information than what https://github.com/canonical/hotsos/issues/198 will, (though that one is not specific to just D state processes, but any task thats blocked longer than default timeout)
