### ISSUE TITLE
compare mysql num open connections with max open file limit

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#76]

**Comment by lathiat** [comment]
This will probably depend on the following upstream commit to get all of /etc/mysql/*:
https://github.com/sosreport/sos/pull/2510

As without that, we can't see the current value of 'max_connections' since the config files weren't collected in most cases. So check for the existence of max_connections:
./percona-xtradb-cluster.conf.d/mysqld.cnf:max_connections = 20000

If we can find a max_connections > 4190 then we should verify that /etc/systemd/system/mysql.service.d/charm-nofile.conf is configured with a value. In theory we could check the actual value but in practice that file was never created until I patched the charm, so if the file exists, it's likely OK. If it doesn't exist, it's not OK if max_connections is > 4190.

**Comment by lathiat** [comment]
Need to also investigate the mysql-8 innodb cluster situation.

**Comment by dosaboy** [comment]
While we are at it lets also check for logs like "[Warning] InnoDB: Difficult to find free blocks in the buffer pool (338 search iterations)! 0 failed attempts to flush a page! Consider increasing the buffer pool size." since that implies that the innodb-buffer-pool-size is too small.

**Comment by dosaboy** [comment]
A bug related to max_connections with mysql-innodb - https://bugs.launchpad.net/charm-mysql-router/+bug/1929826

**Comment by nkshirsagar** [comment]
The log string check for
~~~
"[Warning] InnoDB: Difficult to find free blocks in the buffer pool (338 search iterations)! 0 failed attempts to flush a page! Consider increasing the buffer pool size." since that implies that the innodb-buffer-pool-size is too small.
~~~
seems straightforward to implement as a scenario check or even a bug if a known LP issue exists. Something like,

~~~
checks:
  input:
    path: 'var/log/mysql/error.log'
  free_blocks_difficult:
    expr: '(.+ \d+) (\d+:\d+:\d+) .+ (\S+) Difficult to find free blocks in the buffer pool\:'
conclusions:
  free_blocks_difficult:
        raises:
      type: SQLError
      message: >-
        XXXX <-- some reasonable message or if there's a LP bug already for this, I could do it as a bug itself instead of a scenario
~~~

But for the two properties, /percona-xtradb-cluster.conf.d/mysqld.cnf:max_connections and the existence (or values in it) of the /etc/systemd/system/mysql.service.d/charm-nofile.conf need to be exported and available as properties in the MySQLChecksBase class) which currently looks like
~~~
from hotsos.core.host_helpers import (
    APTPackageChecksBase,
    ServiceChecksBase,
)
from hotsos.core import plugintools


SVC_VALID_SUFFIX = r'[0-9a-zA-Z-_]*'
MYSQL_SVC_EXPRS = [r'mysql{}'.format(SVC_VALID_SUFFIX)]
CORE_APT = ['mysql']


class MySQLChecksBase(plugintools.PluginPartBase):

    def __init__(self, *args, **kwargs):
        super().__init__()
        self.apt_info = APTPackageChecksBase(core_pkgs=CORE_APT)
        self.systemd_info = ServiceChecksBase(service_exprs=MYSQL_SVC_EXPRS)

    @property
    def plugin_runnable(self):
        return self.apt_info.core is not None
~~~
Or is there another way of doing this without the MySQLChecksBase containing those two exported properties?

**Comment by nkshirsagar** [comment]
Hi @dosaboy ,

thanks for the help with how to approach this one. 

So I've done something like this. This is not my final code, just something to check if I am on the right track as far as the config check is concerned. I am sure I can use better logic for the existence of the /etc/systemd/system/mysql.service.d/charm-nofile.conf file itself, here I am checking if it contains any string at all. 

I just wanted to show you this rough approach, note this git diff doesn't contain the code for the bug check for ""[Warning] InnoDB: Difficult to find free blocks in the buffer pool ..." because that part is clearer than this other check for this issue.. 

So this is for the check of whether max_connections is greater than 4190 and if so, yet the charm-nofile.conf file does not exist.

~~~
diff --git a/defs/scenarios/mysql/mysql.yaml b/defs/scenarios/mysql/mysql.yaml
index 4e0ea32a..654bdd69 100644
--- a/defs/scenarios/mysql/mysql.yaml
+++ b/defs/scenarios/mysql/mysql.yaml
@@ -2,3 +2,32 @@
 # directory including subdirectories.
 requires:
   property: hotsos.core.plugins.mysql.MySQLChecksBase.plugin_runnable
+
+checks:
+  max_connections_greater_than_4190:
+    requires:
+      config:
+        handler: hotsos.core.plugins.mysql.MySQLConfig
+        assertions:
+          max_connections:
+            ops: [[gt, 4190]]
+  file_not_exists:
+    input:
+      path: /etc/systemd/system/mysql.service.d/charm-nofile.conf 
+    requires:
+      expr: '(\S+)'
+ 
+conclusions:
+  max_connections_problem:
+    decision:
+      and:
+        - max_connections_greater_than_4190
+        - file_not_exists
+    raises:
+      type: MySQLWarning
+      message: >-
+        Max Connections is higher than 4190 but there is no
+        charm-nofile.conf seen. 
+
+
+
diff --git a/hotsos/core/plugins/mysql.py b/hotsos/core/plugins/mysql.py
index 5dfd1e4a..8b645c78 100644
--- a/hotsos/core/plugins/mysql.py
+++ b/hotsos/core/plugins/mysql.py
@@ -2,8 +2,11 @@ from hotsos.core.host_helpers import (
     APTPackageChecksBase,
     ServiceChecksBase,
 )
-from hotsos.core import plugintools
-
+from hotsos.core import (
+    host_helpers,
+    utils,
+    plugintools
+) 
 
 SVC_VALID_SUFFIX = r'[0-9a-zA-Z-_]*'
 MYSQL_SVC_EXPRS = [r'mysql{}'.format(SVC_VALID_SUFFIX)]
@@ -20,3 +23,10 @@ class MySQLChecksBase(plugintools.PluginPartBase):
     @property
     def plugin_runnable(self):
         return self.apt_info.core is not None
+
+class MySQLConfig(host_helpers.SectionalConfigBase):
+    def __init__(self, *args, **kwargs):
+        path = os.path.join(HotSOSConfig.DATA_ROOT, 'etc/mysql/mysql.conf.d/mysqld.cnf')
+        super().__init__(*args, path=path, **kwargs)
+
+
 ~~~
